{{config(
     materialization='view',
     database='REAL_ESTATE',
     schema='LISTINGS'
)}}

WITH ranked AS (
    SELECT
    PROP_ID,
    CLEAN_CITY_NAME,
    PRICE,
    AGE,
    TOTAL_FLOOR,
    BEDROOM_NUM,


    PERCENT_RANK() OVER(PARTITION BY CLEAN_CITY_NAME ORDER BY PRICE) AS PRICE_SCORE,
    PERCENT_RANK() OVER(PARTITION BY CLEAN_CITY_NAME ORDER BY TOTAL_FLOOR) AS FLOOR_SCORE,
    PERCENT_RANK() OVER(PARTITION BY CLEAN_CITY_NAME ORDER BY BEDROOM_NUM) AS BEDROOM_SCORE,


    1-PERCENT_RANK() OVER(PARTITION BY CLEAN_CITY_NAME ORDER BY AGE) AS AGE_SCORE

FROM REAL_ESTATE.LISTINGS.LISTINGS_CLEANED

),


scored AS (
    SELECT
      *,
      ROUND(
        0.4 * PRICE_score +
        0.2 * AGE_SCORE +
        0.2 * FLOOR_SCORE +
        0.2 * BEDROOM_SCORE, 4
    
      ) AS FINAL_VALUE_SCORE

    FROM ranked
)

luxury_tagged AS (
    SELECT
        *,
        NTILE(10) OVER (PARTITION BY CLEAN_CITY_NAME ORDER BY final_value_score DESC) AS decile,
        CASE
            WHEN NTILE(10) OVER (PARTITION BY CLEAN_CITY_NAME ORDER BY final_value_score DESC) = 1 THEN TRUE
            ELSE FALSE
        END AS is_luxury
    FROM scored
)

SELECT * FROM scored
ORDER BY FINAL_VALUE_SCORE DESC